version: '3.3'
services:
  db:
    image: postgres:13.0-alpine
    volumes:
      - postgresql_db:/var/lib/postgresql/data/
    env_file:
      - ./.env
  web:
    image: gidwin/food_back:latest
    restart: always
    volumes:
      - static_value:/app/backend_static/
      - media_value:/app/backend_media/
    depends_on:
      - db
    env_file:
      - ./.env

  frontend:
    image: gidwin/food_front:latest
    volumes:
      - ../frontend/:/app/result_build/
  nginx:
    image: nginx:1.19.3
    ports:
      - "80:80"
    volumes:
      - ./nginx.conf:/etc/nginx/conf.d/default.conf
      - ../frontend/build:/usr/share/nginx/html/
      - ../docs/:/usr/share/nginx/html/api/docs/
      - static_value:/var/html/backend_static/
      - media_value:/var/html/backend_media/
    depends_on:
      - web

  volumes:
  postgresql_db:
  static_value:
  media_value:
