# Generated by Django 4.1.7 on 2023-03-02 15:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0003_alter_favorite_id_alter_ingredient_id_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='ingredientamount',
            options={'verbose_name': 'Количество ингредиента', 'verbose_name_plural': 'Количество ингридиентов'},
        ),
    ]
